# docker-compose.yml
version: "3"
networks:
  todoapp-net:
services:
  pythonapp:
    image: todoapp:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - ENGINE=django.db.backends.mysql
      - NAME=${DB_NAME}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - HOST=mysql
      - PORT=3306
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
